version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit_message:
      prefix: "[Dependabot]"
    default_labels:
      - "dependabot"
      - "dependencies"
    automerged_updates:
    - match:
        dependency_type: "development"
        update_type: "in_range"
    - match:
        dependency_type: "production"
        update_type: "semver:patch"
