import Arrow from "./Arrow";
import { Calendar } from "./Calendar";
import { CheckMark, CheckMarkCircle } from "./CheckMark";
import Chevron from "./Chevron";
import { Star } from "./Star";
import { Resize } from "./Resize";
import { Password } from "./Password";
import { Forbidden } from "./Forbidden";
import { Bookmark } from "./Bookmark";
import { Flame } from "./Flame";
import { Edit, Pencil } from "./Edit";
import { SwimmingPool } from "./SwimmingPool";
import { Beach, BeachBall, BeachChair, BeachUmbrella } from "./Beach";
import { Sunbed, SunbedWithMatress } from "./Sunbed";
import { TrashBin } from "./TrashBin";
import { Close, CloseCircle } from "./Close";
import Files from "./Files";
import Math from "./Math";
import Navigation from "./Navigation";
import Notification from "./Notification";
import Payment from "./Payment";
import People from "./People";
import Search from "./Search";
import Social from "./Social";
import Logo from "./Logo";

type SubComponents = {
  Chevron: typeof Chevron;
  Arrow: typeof Arrow;
  Math: typeof Math;
  Calendar: typeof Calendar;
  Files: typeof Files;
  Logo: typeof Logo;
  Navigation: typeof Navigation;
  Notification: typeof Notification;
  Payment: typeof Payment;
  People: typeof People;
  Search: typeof Search;
  Social: typeof Social;
  Close: typeof Close;
  CloseCircle: typeof CloseCircle;
  CheckMark: typeof CheckMark;
  CheckMarkCircle: typeof CheckMarkCircle;
  Star: typeof Star;
  Resize: typeof Resize;
  Password: typeof Password;
  Forbidden: typeof Forbidden;
  Bookmark: typeof Bookmark;
  Flame: typeof Flame;
  Pencil: typeof Pencil;
  Edit: typeof Edit;
  SwimmingPool: typeof SwimmingPool;
  Beach: typeof Beach;
  BeachBall: typeof BeachBall;
  BeachChair: typeof BeachChair;
  BeachUmbrella: typeof BeachUmbrella;
  Sunbed: typeof Sunbed;
  SunbedWithMatress: typeof SunbedWithMatress;
  TrashBin: typeof TrashBin;
};

type IconProps = {};

export const Icon: React.FC<IconProps> & SubComponents = () => {
  return <div></div>;
};

Icon.displayName = "Icon";

Icon.Chevron = Chevron;
Icon.Arrow = Arrow;
Icon.Math = Math;
Icon.Calendar = Calendar;
Icon.Files = Files;
Icon.Logo = Logo;
Icon.Navigation = Navigation;
Icon.Navigation = Navigation;
Icon.Notification = Notification;
Icon.Payment = Payment;
Icon.People = People;
Icon.Search = Search;
Icon.Social = Social;
Icon.Close = Close;
Icon.CloseCircle = CloseCircle;
Icon.CheckMark = CheckMark;
Icon.CheckMarkCircle = CheckMarkCircle;
Icon.Star = Star;
Icon.Resize = Resize;
Icon.Password = Password;
Icon.Forbidden = Forbidden;
Icon.Bookmark = Bookmark;
Icon.Flame = Flame;
Icon.Pencil = Pencil;
Icon.Edit = Edit;
Icon.SwimmingPool = SwimmingPool;
Icon.Beach = Beach;
Icon.BeachBall = BeachBall;
Icon.BeachChair = BeachChair;
Icon.BeachUmbrella = BeachUmbrella;
Icon.Sunbed = Sunbed;
Icon.SunbedWithMatress = SunbedWithMatress;
Icon.TrashBin = TrashBin;

export default Icon;
